// Generated by `node scripts/i18n.mjs index` — do not edit.
//
// Every message in the interface, gathered from the area files beside this
// one. Each key carries its area as a prefix, so a line can be traced back to
// the file it came from without a lookup table.

import { aboutProject } from './aboutProject'
import { activityBar } from './activityBar'
import { apiClient } from './apiClient'
import { app } from './app'
import { appShell } from './appShell'
import { appStore } from './appStore'
import { changeLogPane } from './changeLogPane'
import { codegenPane } from './codegenPane'
import { comparePane } from './comparePane'
import { connectionDialog } from './connectionDialog'
import { connectionPostgres } from './connectionPostgres'
import { connectionShared } from './connectionShared'
import { connectionSidebar } from './connectionSidebar'
import { connectionTypeMenu } from './connectionTypeMenu'
import { copyTableModal } from './copyTableModal'
import { dataGenPane } from './dataGenPane'
import { dataGenWorkspace } from './dataGenWorkspace'
import { dataGrid } from './dataGrid'
import { ddlPane } from './ddlPane'
import { designGrid } from './designGrid'
import { erDiagramPane } from './erDiagramPane'
import { exportModal } from './exportModal'
import { libAbout } from './libAbout'
import { libMockCatalog } from './libMockCatalog'
import { libMockCustom } from './libMockCustom'
import { libMockDefaults } from './libMockDefaults'
import { libMockEngine } from './libMockEngine'
import { libTheme } from './libTheme'
import { libTree } from './libTree'
import { mainToolbar } from './mainToolbar'
import { mockPickerModal } from './mockPickerModal'
import { mockPlaceholderSettings } from './mockPlaceholderSettings'
import { objectListPane } from './objectListPane'
import { overviewMongo } from './overviewMongo'
import { overviewShared } from './overviewShared'
import { overviewSqlite } from './overviewSqlite'
import { overviewUnsupported } from './overviewUnsupported'
import { queryFavorites } from './queryFavorites'
import { queryPane } from './queryPane'
import { resizableHeader } from './resizableHeader'
import { rowDetail } from './rowDetail'
import { runSqlFile } from './runSqlFile'
import { runtimePane } from './runtimePane'
import { settingsPane } from './settingsPane'
import { statusBar } from './statusBar'
import { storeApp } from './storeApp'
import { structurePane } from './structurePane'
import { tablePane } from './tablePane'
import { workspace } from './workspace'

/** Every message, keyed by `<area>.<slug>`. */
export const MESSAGES = {
  ...aboutProject,
  ...activityBar,
  ...apiClient,
  ...app,
  ...appShell,
  ...appStore,
  ...changeLogPane,
  ...codegenPane,
  ...comparePane,
  ...connectionDialog,
  ...connectionPostgres,
  ...connectionShared,
  ...connectionSidebar,
  ...connectionTypeMenu,
  ...copyTableModal,
  ...dataGenPane,
  ...dataGenWorkspace,
  ...dataGrid,
  ...ddlPane,
  ...designGrid,
  ...erDiagramPane,
  ...exportModal,
  ...libAbout,
  ...libMockCatalog,
  ...libMockCustom,
  ...libMockDefaults,
  ...libMockEngine,
  ...libTheme,
  ...libTree,
  ...mainToolbar,
  ...mockPickerModal,
  ...mockPlaceholderSettings,
  ...objectListPane,
  ...overviewMongo,
  ...overviewShared,
  ...overviewSqlite,
  ...overviewUnsupported,
  ...queryFavorites,
  ...queryPane,
  ...resizableHeader,
  ...rowDetail,
  ...runSqlFile,
  ...runtimePane,
  ...settingsPane,
  ...statusBar,
  ...storeApp,
  ...structurePane,
  ...tablePane,
  ...workspace,
}

/** The keys a `t` call may use; the type checker knows every one of them. */
export type MessageKey = keyof typeof MESSAGES
