package sqlbase

import (
	"strings"
	"testing"

	"dbmanager/internal/drivers"
	"dbmanager/internal/models"
)

// A copy is rendered by the same code as a CREATE from the designer, so these
// tests pin down the two things the copy adds on top of it: how a live table is
// read as a definition, and what the data statement looks like. The DDL itself is
// already covered by the designer's tests.

// serialStructure is a MySQL-shaped sample with the parts a copy has to be
// careful about: an auto-incrementing key, a serial column and two indexes.
func serialStructure() *models.TableStructure {
	return &models.TableStructure{
		Object: models.ObjectInfo{
			Name:     "orders",
			Database: "shop",
			Schema:   "public",
			Kind:     models.KindTable,
		},
		Columns: []models.ColumnInfo{
			{Name: "id", DataType: "int", ColumnType: "int", PrimaryKey: true, AutoIncrement: true},
			{Name: "user_id", DataType: "int", ColumnType: "int", Nullable: true},
			{Name: "note", DataType: "text", ColumnType: "text", Nullable: true, Comment: "free text"},
		},
		Indexes: []models.IndexInfo{
			{Name: "PRIMARY", Columns: []string{"id"}, Unique: true, Primary: true},
			{Name: "idx_orders_user", Columns: []string{"user_id"}},
		},
	}
}

func planCopy(t *testing.T, dialect drivers.Dialect, structure *models.TableStructure, target string, withData bool) models.DesignPlan {
	t.Helper()
	plan, err := PlanCopy(dialect, structure, target, withData)
	if err != nil {
		t.Fatalf("PlanCopy: %v", err)
	}
	return plan
}

// TestPlanCopyStructureOnly pins the script for the two engines that scope
// index names differently: MySQL reuses the original's name, PostgreSQL cannot.
func TestPlanCopyStructureOnly(t *testing.T) {
	mysql := planCopy(t, MySQLDialect{}, serialStructure(), "orders_copy", false)
	assertStatements(t, mysql.Statements, []string{
		"CREATE TABLE `shop`.`orders_copy` (\n" +
			"  `id` int NOT NULL AUTO_INCREMENT,\n" +
			"  `user_id` int NULL,\n" +
			"  `note` text NULL COMMENT 'free text',\n" +
			"  PRIMARY KEY (`id`)\n" +
			")",
		"CREATE INDEX `idx_orders_user` ON `shop`.`orders_copy` (`user_id`)",
	})
	if len(mysql.Warnings) != 0 {
		t.Fatalf("MySQL keeps an index inside its table, so nothing had to change: %v", mysql.Warnings)
	}
	if mysql.Destructive {
		t.Fatal("copying a table destroys nothing")
	}

	postgres := planCopy(t, PostgresDialect{}, serialStructure(), "orders_copy", false)
	assertStatements(t, postgres.Statements, []string{
		"CREATE TABLE \"public\".\"orders_copy\" (\n" +
			"  \"id\" int GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
			"  \"user_id\" int,\n" +
			"  \"note\" text,\n" +
			"  PRIMARY KEY (\"id\")\n" +
			")",
		"COMMENT ON COLUMN \"public\".\"orders_copy\".\"note\" IS 'free text'",
		"CREATE INDEX \"public\".\"orders_copy_idx_orders_user\" ON \"public\".\"orders_copy\" (\"user_id\")",
	})
	joined := strings.Join(postgres.Warnings, "\n")
	if !strings.Contains(joined, "idx_orders_user is created as orders_copy_idx_orders_user") {
		t.Fatalf("the renamed index must be explained: %v", postgres.Warnings)
	}
}

// TestPlanCopyWithData appends one statement that moves the rows, and it is the
// last one: the table has to exist before anything can be written into it.
func TestPlanCopyWithData(t *testing.T) {
	plan := planCopy(t, MySQLDialect{}, serialStructure(), "orders_copy", true)
	last := plan.Statements[len(plan.Statements)-1]
	want := "INSERT INTO `shop`.`orders_copy` (`id`, `user_id`, `note`)\n" +
		"SELECT `id`, `user_id`, `note`\n" +
		"FROM `shop`.`orders`"
	if last != want {
		t.Fatalf("the data statement:\n got: %s\nwant: %s", last, want)
	}
	if len(plan.Statements) != 3 {
		t.Fatalf("expected the create, the index and the insert, got %v", plan.Statements)
	}
}

// TestPlanCopyReadsTheStructureTheWayTheDesignerDoes pins the mapping from the
// catalog onto a definition, since that mapping is the only part of a copy that
// the designer's own tests cannot cover.
func TestPlanCopyReadsTheStructureTheWayTheDesignerDoes(t *testing.T) {
	structure := serialStructure()
	// A primary key is reported as nullable by some engines; it is the key that
	// rejects NULLs, not the field.
	structure.Columns[0].Nullable = true
	structure.Columns[0].DefaultValue = strptr("7")
	structure.Columns[2].Comment = ""

	design, warnings := designOfCopy(MySQLDialect{}, structure, "orders_copy")
	if len(warnings) != 0 {
		t.Fatalf("nothing here needs a warning: %v", warnings)
	}
	if design.Object != "orders_copy" || design.Database != "shop" || design.Schema != "public" {
		t.Fatalf("the definition lost its place: %+v", design)
	}
	if len(design.Columns) != 3 {
		t.Fatalf("expected three fields, got %+v", design.Columns)
	}
	key := design.Columns[0]
	if !key.PrimaryKey || key.Nullable || !key.AutoIncrement {
		t.Fatalf("the key field lost its flags: %+v", key)
	}
	if key.DefaultValue == nil || *key.DefaultValue != "7" {
		t.Fatalf("a default is copied verbatim: %+v", key.DefaultValue)
	}
	if key.Comment != "" || design.Columns[2].Comment != "" {
		t.Fatalf("an empty comment stays empty: %+v", design.Columns)
	}
	// The primary key belongs on the fields and is not repeated as an index.
	if len(design.Indexes) != 1 || design.Indexes[0].Name != "idx_orders_user" {
		t.Fatalf("unexpected indexes: %+v", design.Indexes)
	}
	if design.Indexes[0].OriginalName != "" {
		t.Fatalf("the copy's indexes come from nowhere: %+v", design.Indexes[0])
	}
}

// TestPlanCopyTurnsASerialColumnIntoAnIdentity covers the trap a verbatim copy
// would walk into: `DEFAULT nextval('orders_id_seq')` points at the *original's*
// counter, so the two tables would share one.
func TestPlanCopyTurnsASerialColumnIntoAnIdentity(t *testing.T) {
	structure := serialStructure()
	structure.Columns[0].DefaultValue = strptr("nextval('orders_id_seq'::regclass)")

	plan := planCopy(t, PostgresDialect{}, structure, "orders_copy", false)
	created := plan.Statements[0]
	if strings.Contains(created, "nextval") {
		t.Fatalf("the copy must not reuse the original's sequence:\n%s", created)
	}
	if !strings.Contains(created, "\"id\" int GENERATED BY DEFAULT AS IDENTITY NOT NULL") {
		t.Fatalf("the key should have become an identity column:\n%s", created)
	}
	if !strings.Contains(strings.Join(plan.Warnings, "\n"), "identity column") {
		t.Fatalf("the substitution must be said out loud: %v", plan.Warnings)
	}

	// A sequence-backed default on something that cannot be an identity column
	// is left alone, and reported instead of replaced with a statement the
	// engine would refuse.
	awkward := serialStructure()
	awkward.Columns[0].DataType = "numeric"
	awkward.Columns[0].ColumnType = "numeric"
	awkward.Columns[0].DefaultValue = strptr("nextval('orders_id_seq'::regclass)")

	plan = planCopy(t, PostgresDialect{}, awkward, "orders_copy", false)
	if !strings.Contains(plan.Statements[0], "DEFAULT nextval('orders_id_seq'::regclass)") {
		t.Fatalf("the default must survive as it was:\n%s", plan.Statements[0])
	}
	if !strings.Contains(strings.Join(plan.Warnings, "\n"), "share one counter") {
		t.Fatalf("the shared counter must be said out loud: %v", plan.Warnings)
	}
}

// TestPlanCopyDataWarnsWhereTheCounterDoesNotFollow: MySQL moves its
// AUTO_INCREMENT past what it just inserted and SQLite takes the largest rowid
// with the rows, but a PostgreSQL identity column keeps counting from 1.
func TestPlanCopyDataWarnsWhereTheCounterDoesNotFollow(t *testing.T) {
	structure := serialStructure()
	structure.Columns[0].DefaultValue = strptr("nextval('orders_id_seq'::regclass)")

	postgres := planCopy(t, PostgresDialect{}, structure, "orders_copy", true)
	if !strings.Contains(strings.Join(postgres.Warnings, "\n"), "starts at 1") {
		t.Fatalf("the identity counter must be mentioned: %v", postgres.Warnings)
	}

	for _, dialect := range []drivers.Dialect{MySQLDialect{}, SQLiteDialect{}} {
		plan := planCopy(t, dialect, serialStructure(), "orders_copy", true)
		for _, warning := range plan.Warnings {
			if strings.Contains(warning, "starts at 1") {
				t.Fatalf("%s moves its counter with the rows: %v", dialect.Name(), plan.Warnings)
			}
		}
	}
}

// TestPlanCopyRefusesWhatItCannotDo: a copy needs a name of its own, and an
// engine with no CREATE renderer has no copy either.
func TestPlanCopyRefusesWhatItCannotDo(t *testing.T) {
	if _, err := PlanCopy(MySQLDialect{}, serialStructure(), "orders", false); err == nil {
		t.Fatal("expected the table being copied to be refused as a target")
	}
	if _, err := PlanCopy(MySQLDialect{}, serialStructure(), "   ", false); err == nil {
		t.Fatal("expected a nameless copy to be refused")
	}
	if _, err := PlanCopy(MySQLDialect{}, &models.TableStructure{}, "orders_copy", false); err == nil {
		t.Fatal("expected a structure without fields to be refused")
	}
	if _, err := PlanCopy(sqlbaseDorisDialect(), serialStructure(), "orders_copy", false); err == nil {
		t.Fatal("expected Doris to have no copy renderer")
	}
}

// sqlbaseDorisDialect is the MySQL dialect under Doris' name, which is exactly
// how the driver wires it.
func sqlbaseDorisDialect() MySQLDialect {
	return MySQLDialect{Driver: models.DriverDoris}
}
